# Generated by Django 2.1.1 on 2019-06-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190613_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_nums',
        ),
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='view_count'),
        ),
    ]
