# Generated by Django 2.1.1 on 2019-06-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190612_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='video/%Y/%m', verbose_name='cover'),
        ),
    ]
